//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiWork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiWorkdbEntities : DbContext
    {
        public DiWorkdbEntities()
            : base("name=DiWorkdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Automoviles> Automoviles { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<Modelos> Modelos { get; set; }
        public virtual DbSet<Motos> Motos { get; set; }
        public virtual DbSet<presupuestos> presupuestos { get; set; }
        public virtual DbSet<PresupuestosxAutomovil> PresupuestosxAutomovil { get; set; }
        public virtual DbSet<PresupuestosxMotos> PresupuestosxMotos { get; set; }
        public virtual DbSet<Repuestos> Repuestos { get; set; }
        public virtual DbSet<RepuestosxPresupuestos> RepuestosxPresupuestos { get; set; }
        public virtual DbSet<TipoAutomoviles> TipoAutomoviles { get; set; }
    }
}
