//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motos()
        {
            this.PresupuestosxMotos = new HashSet<PresupuestosxMotos>();
        }
    
        public int ID { get; set; }
        public int IDModelo { get; set; }
        public string patente { get; set; }
        public Nullable<int> cilindrada { get; set; }
    
        public virtual Modelos Modelos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresupuestosxMotos> PresupuestosxMotos { get; set; }
    }
}
