//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public presupuestos()
        {
            this.RepuestosxPresupuestos = new HashSet<RepuestosxPresupuestos>();
        }
    
        public int ID { get; set; }
        public string descripcion { get; set; }
        public decimal costo { get; set; }
        public int diasTrabajo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepuestosxPresupuestos> RepuestosxPresupuestos { get; set; }
    }
}
